### PR TITLE
Support textarea & remove polling

### PR DESCRIPTION
**Pull request by lokimckay**
- Introduce "targets" - classes which represent a compatible element that Resurface can control
- Remove polling on page load - only run primary functionality when extension icon is clicked
- Support opening multiple Resurface editors at once & controlling different page elements at the same time
- Improve highlighted target appearance with stripes in addition to "Open Resurface editor" button

### CODE REVIEW

**Comment by lokimckay** [comment]
@dtorres-sf this release was just published on the [web store](https://chrome.google.com/webstore/detail/resurface/mcneombcjoaibfjnpodhhngnlhapiocl) today!
I hope it works smoothly for your purposes

Thanks again for your contributions, if you end up making an account and let me know the email, I'd be happy to give you a VIP subscription to remove the watermark for free 😄 

You can DM me on [twitter](https://twitter.com/sneyed) if you don't want to put your email here

**Comment by dtorres-sf** [comment]
@lokimckay love the new changes with the removal of polling. I was originally testing by building from main instead of the web store and hit a lot of issues on textareas especially when there were multiple on a page. But when I downgraded to the published version (1.4.1) it is working great! I appreciate all the new features!!

FYI, I have started looking into Firefox support. I will keep you updated and if it is something I can get working successfully I will open a PR.

**Comment by lokimckay** [comment]
Huh interesting, I did some testing with 2 text areas on a page but didn't notice any issues
I've recently published version 1.4.4 to the webstore - if you noticed any issues with that one could you please let me know how to reproduce them via an [issue](https://github.com/code-cabana/resurface/issues)?

**Pull request merged**
